### ISSUE TITLE
Create form to enable users to post their user details

### ISSUE THREAD

**Issue by useEffects** [coding-club-gct/coding-club-website#9]
![image](https://user-images.githubusercontent.com/80976002/226120971-11ea87f4-44b7-4fbd-89ca-51e74609c2ac.png)

**Comment by iamnoufal** [comment]
Update: We'll ask the students to ask the representatives to talk with the CC board. We'll get CSV from them
Updated message for the popup: Please ask your class representative to get in touch with the club (codingclub@gct.ac.in)
